# Generated by Django 3.2.10 on 2021-12-29 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cno', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='课程号')),
                ('cname', models.CharField(max_length=100, null=True, verbose_name='课程名')),
                ('dept', models.CharField(max_length=100, null=True, verbose_name='开课院系')),
                ('teacher', models.CharField(max_length=20, null=True, verbose_name='开课老师')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='学号')),
                ('sname', models.CharField(max_length=20, null=True, verbose_name='姓名')),
                ('sclass', models.CharField(max_length=20, null=True, verbose_name='班级')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('sage', models.IntegerField(default=0, verbose_name='年龄')),
                ('sdept', models.CharField(max_length=100, null=True, verbose_name='院系')),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=1, max_length=50, verbose_name='认证Token')),
                ('phone', models.CharField(max_length=20)),
                ('identity', models.IntegerField(choices=[(0, '学生'), (1, '老师'), (2, '管理员')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(null=True, verbose_name='成绩')),
                ('cno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Content.course')),
                ('sno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Content.students')),
            ],
        ),
    ]
